### ISSUE TITLE
Cross-folder list test

### ISSUE THREAD

**Issue by labkey-chrisj** [LabKey/platform#3442]
Add test coverage for list behavior in project/subfolder

**Comment by labkey-chrisj** [comment]
- [x] - project-level list, data added to subfolder is scoped
- [x] - same-name list in subfolder as in project
- [x] - metadata is available in subfolder for data in-folder in a top-level defined list
- [x] - subfolder-defined list is not queryable from top level
- [x] - subfolder can contain list with same name as top folder

**Comment by labkey-nicka** [comment]
https://github.com/LabKey/testAutomation/pull/1146
