### ISSUE TITLE
No-question-mark-urls setting and fixing, part 1

### ISSUE THREAD

**Issue by labkey-adam** [LabKey/platform#3617]
Since the beginning of (LabKey) time, LabKey Server has appended question marks to the end of the URLs it renders, even when there are no parameters. This makes it easier to add parameters via string concatenation (myUrl + "&foo=1" is always valid), but it results in amateurish URLs. We also want to discourage string concatenation of params since it's more time consuming and less reliable than using `addParameter()`. In this story we are fixing places in the product and test code that make assumptions about whether URLs are rendered with dangling question marks. Goal is to enable the no-question-mark-urls setting by default, first in dev mode and eventually on production servers. We will then close out the oldest active issue in our list: [Issue 1713: Suppress trailing ? in URL strings if no parameters](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=1713).

- [x] Regex search for likely parameter concatenation. Audit and fix inappropriate assumptions. - (10) @labkey-adam 
- [x] Fix `WebTestHelper.buildUrl()` to match server's ? behavior - (2) @labkey-tchad 
- [x] Review PRs for first round of fixes - (1) @labkey-jeckels 
- [x] Merge first round of fixes - (1) @labkey-adam 
- [x] Fix test failures - (8) @labkey-tchad 
- [x] Run BVT, Daily, External, Custom, etc. suites with flag turned on and fix any remaining assumptions - (5) @labkey-adam 
- [x] Set flag on by default for new servers and test (1) - @labkey-adam 
- [x] Merge change to set flag on by default for new servers and inform team (1) - @labkey-adam

Moved remaining tasks to [No-question-mark-urls setting and fixing, part 2](https://github.com/LabKey/platform/issues/3637)

**Comment by labkey-tchad** [comment]
Remaining work and monitoring moved to backlog
